[package]
name = "raincloud_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.20.0"
linked-hash-map = "0.5.6"
paste = "1.0.15"
